name: CI Model Training

on:
  push:
    paths:
      - 'MLproject/**'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow==2.19.0 pandas scikit-learn joblib
      
      - name: Run training
        run: |
          python MLproject/modelling.py --data_path MLproject/titanic_preprocessed.csv
      
      - name: Upload model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLproject/model.pkl
