name: CI Model Training

on:
  push:
    paths:
      - 'MLproject/**'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.12'
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda env update -f MLproject/conda.yaml
          conda activate titanic_env
      - name: Run MLproject
        shell: bash -l {0}
        run: |
          conda activate titanic_env
          mlflow run MLproject -P data_path=MLproject/titanic_preprocessed.csv
      - uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLproject/model.pkl
